global using System.Linq;
global using System.Text;
global using System.Collections;
global using System.Collections.Generic;
global using System;
global using System.Reflection;
global using SunamoUriWebServices._sunamo.SunamoStringReplace;
global using SunamoUriWebServices._public.SunamoData.Data;
global using SunamoUriWebServices._sunamo.SunamoExceptions;
global using System.Diagnostics;
global using System.Net;
global using System.Web;
global using System.Diagnostics.CodeAnalysis;
global using SunamoUriWebServices;
global using SunamoUriWebServices.Ads;
global using SunamoUriWebServices._sunamo;
global using System.Runtime.InteropServices;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
global using SunamoUriWebServices.Values;
